import type * as j from 'jscodeshift';
import type { ASTv1 } from '@glimmer/syntax';
import type { Type } from 'ast-types/lib/types';
import type recast from 'recast';
import type { ASTPath, Collection } from 'jscodeshift';

export { builders } from 'ember-template-recast';

// Re-export all jscodeshift types
export type ASTNode = j.ASTNode;

export type AnyTypeAnnotation = j.AnyTypeAnnotation;
export type ArrayExpression = j.ArrayExpression;
export type ArrayPattern = j.ArrayPattern;
export type ArrayTypeAnnotation = j.ArrayTypeAnnotation;
export type ArrowFunctionExpression = j.ArrowFunctionExpression;
export type AssignmentExpression = j.AssignmentExpression;
export type AssignmentPattern = j.AssignmentPattern;
export type AwaitExpression = j.AwaitExpression;
export type BigIntLiteral = j.BigIntLiteral;
export type BigIntLiteralTypeAnnotation = j.BigIntLiteralTypeAnnotation;
export type BigIntTypeAnnotation = j.BigIntTypeAnnotation;
export type BinaryExpression = j.BinaryExpression;
export type BindExpression = j.BindExpression;
export type Block = j.Block;
export type BlockStatement = j.BlockStatement;
export type BooleanLiteral = j.BooleanLiteral;
export type BooleanLiteralTypeAnnotation = j.BooleanLiteralTypeAnnotation;
export type BooleanTypeAnnotation = j.BooleanTypeAnnotation;
export type BreakStatement = j.BreakStatement;
export type CallExpression = j.CallExpression;
export type CatchClause = j.CatchClause;
export type ChainElement = j.ChainElement;
export type ChainExpression = j.ChainExpression;
export type ClassBody = j.ClassBody;
export type ClassDeclaration = j.ClassDeclaration;
export type ClassExpression = j.ClassExpression;
export type ClassImplements = j.ClassImplements;
export type ClassMethod = j.ClassMethod;
export type ClassPrivateMethod = j.ClassPrivateMethod;
export type ClassPrivateProperty = j.ClassPrivateProperty;
export type ClassProperty = j.ClassProperty;
export type ClassPropertyDefinition = j.ClassPropertyDefinition;
export type Comment = j.Comment;
export type CommentBlock = j.CommentBlock;
export type CommentLine = j.CommentLine;
export type ComprehensionBlock = j.ComprehensionBlock;
export type ComprehensionExpression = j.ComprehensionExpression;
export type ConditionalExpression = j.ConditionalExpression;
export type ContinueStatement = j.ContinueStatement;
export type DebuggerStatement = j.DebuggerStatement;
export type Declaration = j.Declaration;
export type DeclareClass = j.DeclareClass;
export type DeclaredPredicate = j.DeclaredPredicate;
export type DeclareExportAllDeclaration = j.DeclareExportAllDeclaration;
export type DeclareExportDeclaration = j.DeclareExportDeclaration;
export type DeclareFunction = j.DeclareFunction;
export type DeclareInterface = j.DeclareInterface;
export type DeclareModule = j.DeclareModule;
export type DeclareModuleExports = j.DeclareModuleExports;
export type DeclareOpaqueType = j.DeclareOpaqueType;
export type DeclareTypeAlias = j.DeclareTypeAlias;
export type DeclareVariable = j.DeclareVariable;
export type Decorator = j.Decorator;
export type Directive = j.Directive;
export type DirectiveLiteral = j.DirectiveLiteral;
export type DoExpression = j.DoExpression;
export type DoWhileStatement = j.DoWhileStatement;
export type EmptyStatement = j.EmptyStatement;
export type EmptyTypeAnnotation = j.EmptyTypeAnnotation;
export type EnumBooleanBody = j.EnumBooleanBody;
export type EnumBooleanMember = j.EnumBooleanMember;
export type EnumDeclaration = j.EnumDeclaration;
export type EnumDefaultedMember = j.EnumDefaultedMember;
export type EnumNumberBody = j.EnumNumberBody;
export type EnumNumberMember = j.EnumNumberMember;
export type EnumStringBody = j.EnumStringBody;
export type EnumStringMember = j.EnumStringMember;
export type EnumSymbolBody = j.EnumSymbolBody;
export type ExistentialTypeParam = j.ExistentialTypeParam;
export type ExistsTypeAnnotation = j.ExistsTypeAnnotation;
export type ExportAllDeclaration = j.ExportAllDeclaration;
export type ExportBatchSpecifier = j.ExportBatchSpecifier;
export type ExportDeclaration = j.ExportDeclaration;
export type ExportDefaultDeclaration = j.ExportDefaultDeclaration;
export type ExportDefaultSpecifier = j.ExportDefaultSpecifier;
export type ExportNamedDeclaration = j.ExportNamedDeclaration;
export type ExportNamespaceSpecifier = j.ExportNamespaceSpecifier;
export type ExportSpecifier = j.ExportSpecifier;
export type Expression = j.Expression;
export type ExpressionStatement = j.ExpressionStatement;
export type File = j.File;
export type Flow = j.Flow;
export type FlowPredicate = j.FlowPredicate;
export type FlowType = j.FlowType;
export type ForAwaitStatement = j.ForAwaitStatement;
export type ForInStatement = j.ForInStatement;
export type ForOfStatement = j.ForOfStatement;
export type ForStatement = j.ForStatement;
export type Function = j.Function;
export type FunctionDeclaration = j.FunctionDeclaration;
export type FunctionExpression = j.FunctionExpression;
export type FunctionTypeAnnotation = j.FunctionTypeAnnotation;
export type FunctionTypeParam = j.FunctionTypeParam;
export type GeneratorExpression = j.GeneratorExpression;
export type GenericTypeAnnotation = j.GenericTypeAnnotation;
export type Identifier = j.Identifier;
export type IfStatement = j.IfStatement;
export type Import = j.Import;
export type ImportDeclaration = j.ImportDeclaration;
export type ImportDefaultSpecifier = j.ImportDefaultSpecifier;
export type ImportExpression = j.ImportExpression;
export type ImportNamespaceSpecifier = j.ImportNamespaceSpecifier;
export type ImportSpecifier = j.ImportSpecifier;
export type InferredPredicate = j.InferredPredicate;
export type InterfaceDeclaration = j.InterfaceDeclaration;
export type InterfaceExtends = j.InterfaceExtends;
export type InterfaceTypeAnnotation = j.InterfaceTypeAnnotation;
export type InterpreterDirective = j.InterpreterDirective;
export type IntersectionTypeAnnotation = j.IntersectionTypeAnnotation;
export type JSXAttribute = j.JSXAttribute;
export type JSXClosingElement = j.JSXClosingElement;
export type JSXClosingFragment = j.JSXClosingFragment;
export type JSXElement = j.JSXElement;
export type JSXEmptyExpression = j.JSXEmptyExpression;
export type JSXExpressionContainer = j.JSXExpressionContainer;
export type JSXFragment = j.JSXFragment;
export type JSXIdentifier = j.JSXIdentifier;
export type JSXMemberExpression = j.JSXMemberExpression;
export type JSXNamespacedName = j.JSXNamespacedName;
export type JSXOpeningElement = j.JSXOpeningElement;
export type JSXOpeningFragment = j.JSXOpeningFragment;
export type JSXSpreadAttribute = j.JSXSpreadAttribute;
export type JSXSpreadChild = j.JSXSpreadChild;
export type JSXText = j.JSXText;
export type LabeledStatement = j.LabeledStatement;
export type Line = j.Line;
export type Literal = j.Literal;
export type LogicalExpression = j.LogicalExpression;
export type MemberExpression = j.MemberExpression;
export type MemberTypeAnnotation = j.MemberTypeAnnotation;
export type MetaProperty = j.MetaProperty;
export type MethodDefinition = j.MethodDefinition;
export type MixedTypeAnnotation = j.MixedTypeAnnotation;
export type ModuleSpecifier = j.ModuleSpecifier;
export type NewExpression = j.NewExpression;
export type Node = j.Node;
export type Noop = j.Noop;
export type NullableTypeAnnotation = j.NullableTypeAnnotation;
export type NullLiteral = j.NullLiteral;
export type NullLiteralTypeAnnotation = j.NullLiteralTypeAnnotation;
export type NullTypeAnnotation = j.NullTypeAnnotation;
export type NumberLiteralTypeAnnotation = j.NumberLiteralTypeAnnotation;
export type NumberTypeAnnotation = j.NumberTypeAnnotation;
export type NumericLiteral = j.NumericLiteral;
export type NumericLiteralTypeAnnotation = j.NumericLiteralTypeAnnotation;
export type ObjectExpression = j.ObjectExpression;
export type ObjectMethod = j.ObjectMethod;
export type ObjectPattern = j.ObjectPattern;
export type ObjectProperty = j.ObjectProperty;
export type ObjectTypeAnnotation = j.ObjectTypeAnnotation;
export type ObjectTypeCallProperty = j.ObjectTypeCallProperty;
export type ObjectTypeIndexer = j.ObjectTypeIndexer;
export type ObjectTypeInternalSlot = j.ObjectTypeInternalSlot;
export type ObjectTypeProperty = j.ObjectTypeProperty;
export type ObjectTypeSpreadProperty = j.ObjectTypeSpreadProperty;
export type OpaqueType = j.OpaqueType;
export type OptionalCallExpression = j.OptionalCallExpression;
export type OptionalMemberExpression = j.OptionalMemberExpression;
export type ParenthesizedExpression = j.ParenthesizedExpression;
export type Pattern = j.Pattern;
export type Position = j.Position;
export type Printable = j.Printable;
export type PrivateName = j.PrivateName;
export type Program = j.Program;
export type Property = j.Property;
export type PropertyPattern = j.PropertyPattern;
export type QualifiedTypeIdentifier = j.QualifiedTypeIdentifier;
export type RegExpLiteral = j.RegExpLiteral;
export type RestElement = j.RestElement;
export type RestProperty = j.RestProperty;
export type ReturnStatement = j.ReturnStatement;
export type SequenceExpression = j.SequenceExpression;
export type SourceLocation = j.SourceLocation;
export type Specifier = j.Specifier;
export type SpreadElement = j.SpreadElement;
export type SpreadElementPattern = j.SpreadElementPattern;
export type SpreadProperty = j.SpreadProperty;
export type SpreadPropertyPattern = j.SpreadPropertyPattern;
export type Statement = j.Statement;
export type StringLiteral = j.StringLiteral;
export type StringLiteralTypeAnnotation = j.StringLiteralTypeAnnotation;
export type StringTypeAnnotation = j.StringTypeAnnotation;
export type Super = j.Super;
export type SwitchCase = j.SwitchCase;
export type SwitchStatement = j.SwitchStatement;
export type SymbolTypeAnnotation = j.SymbolTypeAnnotation;
export type TaggedTemplateExpression = j.TaggedTemplateExpression;
export type TemplateElement = j.TemplateElement;
export type TemplateLiteral = j.TemplateLiteral;
export type ThisExpression = j.ThisExpression;
export type ThisTypeAnnotation = j.ThisTypeAnnotation;
export type ThrowStatement = j.ThrowStatement;
export type TryStatement = j.TryStatement;
export type TSAnyKeyword = j.TSAnyKeyword;
export type TSArrayType = j.TSArrayType;
export type TSAsExpression = j.TSAsExpression;
export type TSBigIntKeyword = j.TSBigIntKeyword;
export type TSBooleanKeyword = j.TSBooleanKeyword;
export type TSCallSignatureDeclaration = j.TSCallSignatureDeclaration;
export type TSConditionalType = j.TSConditionalType;
export type TSConstructorType = j.TSConstructorType;
export type TSConstructSignatureDeclaration = j.TSConstructSignatureDeclaration;
export type TSDeclareFunction = j.TSDeclareFunction;
export type TSDeclareMethod = j.TSDeclareMethod;
export type TSEnumDeclaration = j.TSEnumDeclaration;
export type TSEnumMember = j.TSEnumMember;
export type TSExportAssignment = j.TSExportAssignment;
export type TSExpressionWithTypeArguments = j.TSExpressionWithTypeArguments;
export type TSExternalModuleReference = j.TSExternalModuleReference;
export type TSFunctionType = j.TSFunctionType;
export type TSHasOptionalTypeAnnotation = j.TSHasOptionalTypeAnnotation;
export type TSHasOptionalTypeParameterInstantiation =
  j.TSHasOptionalTypeParameterInstantiation;
export type TSHasOptionalTypeParameters = j.TSHasOptionalTypeParameters;
export type TSImportEqualsDeclaration = j.TSImportEqualsDeclaration;
export type TSImportType = j.TSImportType;
export type TSIndexedAccessType = j.TSIndexedAccessType;
export type TSIndexSignature = j.TSIndexSignature;
export type TSInferType = j.TSInferType;
export type TSInterfaceBody = j.TSInterfaceBody;
export type TSInterfaceDeclaration = j.TSInterfaceDeclaration;
export type TSIntersectionType = j.TSIntersectionType;
export type TSLiteralType = j.TSLiteralType;
export type TSMappedType = j.TSMappedType;
export type TSMethodSignature = j.TSMethodSignature;
export type TSModuleBlock = j.TSModuleBlock;
export type TSModuleDeclaration = j.TSModuleDeclaration;
export type TSNamedTupleMember = j.TSNamedTupleMember;
export type TSNamespaceExportDeclaration = j.TSNamespaceExportDeclaration;
export type TSNeverKeyword = j.TSNeverKeyword;
export type TSNonNullExpression = j.TSNonNullExpression;
export type TSNullKeyword = j.TSNullKeyword;
export type TSNumberKeyword = j.TSNumberKeyword;
export type TSObjectKeyword = j.TSObjectKeyword;
export type TSOptionalType = j.TSOptionalType;
export type TSParameterProperty = j.TSParameterProperty;
export type TSParenthesizedType = j.TSParenthesizedType;
export type TSPropertySignature = j.TSPropertySignature;
export type TSQualifiedName = j.TSQualifiedName;
export type TSRestType = j.TSRestType;
export type TSStringKeyword = j.TSStringKeyword;
export type TSSymbolKeyword = j.TSSymbolKeyword;
export type TSThisType = j.TSThisType;
export type TSTupleType = j.TSTupleType;
export type TSType = j.TSType;
export type TSTypeAliasDeclaration = j.TSTypeAliasDeclaration;
export type TSTypeAnnotation = j.TSTypeAnnotation;
export type TSTypeAssertion = j.TSTypeAssertion;
export type TSTypeLiteral = j.TSTypeLiteral;
export type TSTypeOperator = j.TSTypeOperator;
export type TSTypeParameter = j.TSTypeParameter;
export type TSTypeParameterDeclaration = j.TSTypeParameterDeclaration;
export type TSTypeParameterInstantiation = j.TSTypeParameterInstantiation;
export type TSTypePredicate = j.TSTypePredicate;
export type TSTypeQuery = j.TSTypeQuery;
export type TSTypeReference = j.TSTypeReference;
export type TSUndefinedKeyword = j.TSUndefinedKeyword;
export type TSUnionType = j.TSUnionType;
export type TSUnknownKeyword = j.TSUnknownKeyword;
export type TSVoidKeyword = j.TSVoidKeyword;
export type TupleTypeAnnotation = j.TupleTypeAnnotation;
export type TypeAlias = j.TypeAlias;
export type TypeAnnotation = j.TypeAnnotation;
export type TypeCastExpression = j.TypeCastExpression;
export type TypeofTypeAnnotation = j.TypeofTypeAnnotation;
export type TypeParameter = j.TypeParameter;
export type TypeParameterDeclaration = j.TypeParameterDeclaration;
export type TypeParameterInstantiation = j.TypeParameterInstantiation;
export type UnaryExpression = j.UnaryExpression;
export type UnionTypeAnnotation = j.UnionTypeAnnotation;
export type UpdateExpression = j.UpdateExpression;
export type VariableDeclaration = j.VariableDeclaration;
export type VariableDeclarator = j.VariableDeclarator;
export type Variance = j.Variance;
export type VoidTypeAnnotation = j.VoidTypeAnnotation;
export type WhileStatement = j.WhileStatement;
export type WithStatement = j.WithStatement;
export type YieldExpression = j.YieldExpression;

// Export Glimmer AST types
export type GlimmerNode = ASTv1.Node;
export type GlimmerStripFlags = ASTv1.StripFlags;
export type GlimmerCommonProgram = ASTv1.CommonProgram;
export type GlimmerBlock = ASTv1.Block;
export type GlimmerTemplate = ASTv1.Template;
export type GlimmerCallNode = ASTv1.CallNode;
export type GlimmerMustacheStatement = ASTv1.MustacheStatement;
export type GlimmerBlockStatement = ASTv1.BlockStatement;
export type GlimmerElementModifierStatement = ASTv1.ElementModifierStatement;
export type GlimmerCommentStatement = ASTv1.CommentStatement;
export type GlimmerMustacheCommentStatement = ASTv1.MustacheCommentStatement;
export type GlimmerElementNode = ASTv1.ElementNode;
export type GlimmerAttrNode = ASTv1.AttrNode;
export type GlimmerTextNode = ASTv1.TextNode;
export type GlimmerConcatStatement = ASTv1.ConcatStatement;
export type GlimmerSubExpression = ASTv1.SubExpression;
export type GlimmerThisHead = ASTv1.ThisHead;
export type GlimmerAtHead = ASTv1.AtHead;
export type GlimmerVarHead = ASTv1.VarHead;
export type GlimmerPathExpression = ASTv1.PathExpression;
export type GlimmerStringLiteral = ASTv1.StringLiteral;
export type GlimmerBooleanLiteral = ASTv1.BooleanLiteral;
export type GlimmerNumberLiteral = ASTv1.NumberLiteral;
export type GlimmerUndefinedLiteral = ASTv1.UndefinedLiteral;
export type GlimmerNullLiteral = ASTv1.NullLiteral;
export type GlimmerHash = ASTv1.Hash;
export type GlimmerHashPair = ASTv1.HashPair;

interface GlimmerNamedTypes {
  GlimmerNode: Type<ASTv1.Node>;
  GlimmerStripFlags: Type<ASTv1.StripFlags>;
  GlimmerCommonProgram: Type<ASTv1.CommonProgram>;
  GlimmerBlock: Type<ASTv1.Block>;
  GlimmerTemplate: Type<ASTv1.Template>;
  GlimmerCallNode: Type<ASTv1.CallNode>;
  GlimmerMustacheStatement: Type<ASTv1.MustacheStatement>;
  GlimmerBlockStatement: Type<ASTv1.BlockStatement>;
  GlimmerElementModifierStatement: Type<ASTv1.ElementModifierStatement>;
  GlimmerCommentStatement: Type<ASTv1.CommentStatement>;
  GlimmerMustacheCommentStatement: Type<ASTv1.MustacheCommentStatement>;
  GlimmerElementNode: Type<ASTv1.ElementNode>;
  GlimmerAttrNode: Type<ASTv1.AttrNode>;
  GlimmerTextNode: Type<ASTv1.TextNode>;
  GlimmerConcatStatement: Type<ASTv1.ConcatStatement>;
  GlimmerSubExpression: Type<ASTv1.SubExpression>;
  GlimmerThisHead: Type<ASTv1.ThisHead>;
  GlimmerAtHead: Type<ASTv1.AtHead>;
  GlimmerVarHead: Type<ASTv1.VarHead>;
  GlimmerPathExpression: Type<ASTv1.PathExpression>;
  GlimmerStringLiteral: Type<ASTv1.StringLiteral>;
  GlimmerBooleanLiteral: Type<ASTv1.BooleanLiteral>;
  GlimmerNumberLiteral: Type<ASTv1.NumberLiteral>;
  GlimmerUndefinedLiteral: Type<ASTv1.UndefinedLiteral>;
  GlimmerNullLiteral: Type<ASTv1.NullLiteral>;
  GlimmerHash: Type<ASTv1.Hash>;
  GlimmerHashPair: Type<ASTv1.HashPair>;
}

export function glimmerCodeshift(
  codeshift: j.JSCodeshift,
  parser?: j.Parser,
): j.JSCodeshift & GlimmerNamedTypes;

export function print(
  ast: ASTPath<unknown> | Collection<unknown>,
  options?: recast.Options,
): string;
